### ISSUE TITLE
No module named dolfin

### ISSUE THREAD

**Issue by JeanRintoul** [nschloe/maelstrom#18]
I just cloned the repo and tried to go through the readme aka pytest but doesn't work. Love an updated readme. Thanks! It gets error that I need a module called dolfin.

**Comment by nschloe** [comment]
Yeah, maelstrom needs a proper overhaul. I'm looking at it now to stitch up the most apparent failures. The rest will follow next year.

**Comment by nschloe** [comment]
I'll look at this once FEniCS 2017.2 is released -- this should be in about two few weeks.

**Comment by nschloe** [comment]
I've now updated maelstrom to use FEniCS 2017.2. Simply install dolfin and it all should work.
